# pnpm workspace configuration
# See: https://pnpm.io/workspaces

packages:
  # Applications
  - 'apps/*'

  # Shared packages
  - 'packages/*'

# Catalog for shared dependency versions
# Use in package.json as: "dependency": "catalog:"
catalog:
  # Core runtime
  typescript: 5.7.2

  # Frontend
  next: 15.1.3
  react: 18.3.1
  react-dom: 18.3.1

  # State management
  '@reduxjs/toolkit': 2.5.0
  react-redux: 9.1.2

  # Backend
  '@nestjs/common': 10.4.15
  '@nestjs/core': 10.4.15
  '@nestjs/platform-express': 10.4.15

  # Database
  '@prisma/client': 6.2.1
  prisma: 6.2.1

  # Testing
  vitest: 2.1.8
  playwright: 1.49.1
  '@playwright/test': 1.49.1

  # Utilities
  date-fns: 4.1.0
  zod: 3.24.1

  # Dev tools
  eslint: 9.17.0
  prettier: 3.4.2
  tsx: 4.19.2
